### ISSUE TITLE
docker-compose build --no-cache returns "ut99-server.build contains an invalid type"

### ISSUE THREAD

**Issue by ghost** [Roemer/ut99-server#13]
Running fedora arm on raspberry pi 3

"The Compose file './docker-compose.yml' is invalid because:
services.ut99-server.build contains an invalid type, it should be a string, or an object

**Comment by yattaro** [comment]
There's a typo in the Compose file that's fixed in the PRs #10 and #12 but neither have been merged yet.  Regardless this Docker image pulls in the official UT99 server package and the OldUnreal update patches, which were only compiled for i686 and unfortunately will not run on your Raspberry Pi.

**Comment by Roemer** [comment]
I merged one of the fixes. Regarding ARM: Does anybody know if it would be possible or an ARM version exists? If so please create a new issue so we could tackle that.
