### ISSUE TITLE
a couple of questions

### ISSUE THREAD

**Issue by moebiusmania** [Roemer/ut99-server#2]
hi, thanks a lot for the great job, I'm living again some damn good old school fragging with friends thanks to this repo!

I have just some questions:
1. there is any way to add some maps to package? ( especially the **DM-Morbias][** )
2. How to set bots difficulty? 

cheers

**Comment by Roemer** [comment]
Great that you enjoy it!
1. If you have mapped the /ut-data folder somewhere, you can modify the maps there or add new maps.
2. You can use the command-line or the web-interface (under port 5580) to modify the bot settings.

DM-Morbias][ should be a default map, so it should already be there? Maybe just not in the default rotation and only in DM of course.

**Comment by moebiusmania** [comment]
1. thanks @Roemer , this will be very handy to add custom maps
2. I'm accessing the web-interface but there isn't any item related to bot difficulty, I will check the command line options

this is the list of the DM maps available in the server
![ut-server](https://user-images.githubusercontent.com/1764542/87203342-ae4f3980-c302-11ea-87a5-f535ce5087ee.png)
those are less from the regular pool of maps available in the client game, DM-Morbias][ is among the ones missing. Do you have any idea why?

**Comment by Roemer** [comment]
On the right side, you have the button `Defaults`. Click on that and you get a lot more settings. Like the Map List, Rules and Bots. There you can choose the game type and then modify the map cycle. Only the maps that are added to the cycle can be chosen from the web-ui in the `current` game. Although I think you can select all maps via the map vote.

**Comment by moebiusmania** [comment]
oh gosh, I thought that was a "restore to defaults settings" button! 🤣
thanks a lot for supporting my dumb questions.
have a nice weekend
