### ISSUE TITLE
Missing weapons

### ISSUE THREAD

**Issue by jimmycann** [Roemer/ut99-server#4]
Hey mate, just set this up to play with some mates, super easy to get up and going, much appreciated!

Having some trouble getting items to load into the game, currently only loading with the shock rifle, nothing else. Would you know how I can enable the rest of the weapons?

Using the default config in the README
CTF-Face?game=BotPack.CTFGame?mutator=BotPack.InstaGibDM,MapVoteLAv2.BDBMapVote,FlagAnnouncementsV2.FlagAnnouncements

Thanks again!

**Comment by Roemer** [comment]
This is due to the InstaGib mod. Disable instagib and you get normal weapons and ammo.

**Comment by jimmycann** [comment]
Ahh cool, thanks for that! :D
